### ISSUE TITLE
OMEMO for group chats

### ISSUE THREAD

**Issue by bendem** [tigase/beagle-im#1]
**Is your feature request related to a problem? Please describe.**
I've been getting into XMPP and I could send encrypted messages to people privately, but I see no option to do that for groups.

**Describe the solution you'd like**
Same feature for groups and private messages

**Describe alternatives you've considered**
I could use another app that supports it, but I don't know of any

**Additional context**
I don't know what I'm doing

**Comment by bendem** [comment]
Alright, I'll be waiting for this feature.

**Comment by stevenroose** [comment]
Any update on this?

**Comment by hantu85** [comment]
It will be part of the next release, but that will be a big release.

**Comment by michaelblyons** [comment]
Hooray stable release! 🎉
