### ISSUE TITLE
Cannot remove contact or channel from contact list

### ISSUE THREAD

**Issue by foss-** [tigase/beagle-im#102]
**Describe the bug**
Unclear how to leave chat and remove the contact from contact list.

**To Reproduce**
1. join general@channels.snikket.org
2. this adds snikket to contacts list and shows snikket chat in Conversation list
3. there is no ellipsis icon at the top right of the chat view - only a telephone icon and `i` icon which does not show an option to leave chat or remove contact
4. click `x` in conversations view to close chat
5. right-click Snikket in contacts list and click `remove`

**Expected behavior**
Contact to be removed from contacts list but this is not happening. Contact remains and there is no means to get rid of the contact.

**Desktop (please complete the following information):**
 - macOS 12.2.1
 - Beagle 5.1

**Comment by hantu85** [comment]
I've just tried to reproduce the issue and the contact was not added to the contact list.

**Comment by foss-** [comment]
macOS 12.4, Beagle 5.2
No longer able to reproduce.

When clicking `x` on Conversation list, Snikket vanishes from Contacts List > All. Closing issue.
