### ISSUE TITLE
Version 5.2 (149) crashing after some time: TigaseSQLite3.DBError.sqliteError(errorCode: 1, message: Optional("near \"(\": syntax error"))

### ISSUE THREAD

**Issue by foss-** [tigase/beagle-im#103]
macOS 12.3
Beagle 5.2 (149) beta

**Describe the bug**
Beagle crashing reproducible after being open for a brief moment (under 1 minute, but not instant)

**To Reproduce**
open latest beta

**Expected behavior**
no crash

**Crash log** (1 year)
https://bin.disroot.org/?cb1809c23acf3c11#84ZgxLUZX9Riis5Yc6NMXWD2uig3kYdpZFuHMgDv3GVr

**Comment by hantu85** [comment]
There is an issue which was introduced in 20860c66a921a36bc231291adfcb11d961a13315. I'll fix it soon and release fixed version.

**Comment by hantu85** [comment]
This should be now fixed in version 5.2-b150.

**Comment by foss-** [comment]
Confirming 5.2 (150) no longer crashes. Thanks for the quick patch.
