### ISSUE TITLE
Constant crashes when joined to 2 group chat rooms with the same room name

### ISSUE THREAD

**Issue by gregkare** [tigase/beagle-im#11]
**Describe the bug**
Crashes when two group chats from two different servers have the same room name. I'm not talking about the same JID, but the description ("Room name"). In my case I'm in the Ops room on my company server, as well as the one for an open source project

**To Reproduce**
1. Join two servers
2. Join a room with the same room name on two different servers
3. Beagle crashes frequently, both on startup and

**Expected behavior**
It should not crash. As a workaround I renamed one of the rooms to have a different room name

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Version 3.5 (also happened with 3.4)

**Comment by gregkare** [comment]
OK, now I can't reproduce it anymore, after renaming the second room to the same name. I wanted to post the crash log and a screenshot.

**Comment by hantu85** [comment]
Is it possible, that not the name was the issue here? we had some issues with crashes on macOS 10.14 and fix is being tested internally right now.

**Comment by gregkare** [comment]
That is indeed possible that the issue was caused by something else than the room name.

A colleague and I are also seeing an issue with rooms disappearing from the side bar when new messages are sent to them, are you aware of this one? Should I create another issue for this?

**Comment by hantu85** [comment]
This "disappearing" and "crashes" are related and appear only on macOS 10.14 while working fine on macOS 10.15.

**Comment by gregkare** [comment]
Thanks, I will close this issue then and will wait for a new release
