### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by shrimpgo** [tigase/beagle-im#113]
**Is your feature request related to a problem? Please describe.**
Actually, it's not a problem. Just a feature that I want to suggest.

**Describe the solution you'd like**
Many others XMPP clients support pasting image from clipboard and this feature will be good for the app. The process is copy an image to a clipboard (from SO) and paste into chat.

**Describe alternatives you've considered**
The only way to do that is saving the image into a file and then upload it to chat.

**Additional context**
I appreciate if you guys give an effort to add this feature. I miss it a lot!

**Comment by woj-tek** [comment]
There is already such feature request: https://github.com/tigase/beagle-im/issues/49
