### ISSUE TITLE
Messages sent/received on other clients do not show up

### ISSUE THREAD

**Issue by jfk9w** [tigase/beagle-im#114]
**Describe the bug**
When Beagle is offline and I send and receive messages on other devices, these messages do not show up in Beagle when it comes online.

**To Reproduce**
1. Quit Beagle.
2. Send/receive some messages from another device (I use Conversations on Android).
3. Re-open Beagle and check for sent/received messages. 

**Expected behavior**
Sent/received messages on other devices should show up in Beagle after coming online (seems like it's what XEP-0313 for?). 

**Desktop:**
 - OS: macOS 12.5 M1 Pro
 - Beagle version: 5.3.1 (162)

**Additional context**
Conversations client seems to support this and exposes all chat history when it comes online.

**Comment by hantu85** [comment]
BeagleIM supports XEP-0313 (MAM) for a quite long time now. Please check your account configuration in BeagleIM ("Archivng settings" if I recall correctly) if automatic synchronization is enabled.

**Comment by jfk9w** [comment]
My bad. Thanks you for help!
