### ISSUE TITLE
Beagle crashing after selecting an emoji

### ISSUE THREAD

**Issue by foss-** [tigase/beagle-im#12]
**Describe the bug**

Beagle reproducibly crashes after trying to insert an emoji in MUC. 100% reproducible.

**To Reproduce**
1. in an xmpp room with cursor in the compose field press ctrl + cmd + space to ope nemoji selection
2. select any emoji

**Expected behavior**
Emoji should show in compose field.

**Current behavior**
Beagle crashes.

 - OS: macOS 10.15.3
 - Version 3.5 (73)

**Additional context**
Crash log is here (1 month): https://bin.disroot.org/?ede738e396106e33#33xmvAh6dGFJtFWSF4CixzsQVYiWYFq98Cj4oBYpNgZV

**Comment by woj-tek** [comment]
This is a know issue and is fixed in version 3.6 - please upgrade to the newest version.

**Comment by foss-** [comment]
fix verified w 3.6. outstanding - thanks for the quick reply and fix. 😎
