### ISSUE TITLE
List BeagleIM.app on Homebrew casks

### ISSUE THREAD

**Issue by michaelblyons** [tigase/beagle-im#13]
**Is your feature request related to a problem? Please describe.**
I don't use the Mac App Store for application management.

**Describe the solution you'd like**
Add your releases to [Homebrew][brew]'s `brew cask` listing. There is a very straightforward sample in the instructions for [how to add a cask][add-cask].

**Describe alternatives you've considered**
It sounds a little silly, but I only made an account for the App Store _for this app._ It took 6 months of dithering to decide it was probably worth it. It's conceivable that others have the same roadblock to use.

[brew]: https://brew.sh
[add-cask]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by hantu85** [comment]
Thank you for the suggestion. We are already publishing builds of BeagleIM at GitHub in the releases, see https://github.com/tigase/beagle-im/releases.

**Comment by michaelblyons** [comment]
It looks like someone [tried to submit Beagle](https://github.com/Homebrew/homebrew-cask/pull/75450) in the past, and was rejected for having <50 GitHub stars. 😢

**Comment by woj-tek** [comment]
A couple of comments @michaelblyons:
* both BeagleIM and Homebrew are opensource so everyone can submit PR
* "A self-submitted app from a GitHub repository that is not notable enough (under 50 stars)." - it seems it would be better if the app would be submitted NOT by Tigase team (self-submission inclusion)
* it seems that if you want it submitted to Homberew then it would be awesome to promote it more and encourage your friends, buddies and contacts to start it on github (we wouldn't mind doing it also for our other projects: [iOS SiskinIM](https://github.com/tigase/siskin-im/), [Tigase XMPP Server](https://github.com/tigase/tigase-server/), [Android StorkIM](https://github.com/tigase/stork) :-)

**Comment by michaelblyons** [comment]
> Both BeagleIM and Homebrew are open source so everyone can submit PR.

That is true. I didn't know until yesterday that it is fine to submit someone else's project to Homebrew. 

As for Beagle itself, I haven't done very much MacOS platform work, but I might try to write something. 🤷‍♂ I'm using MacOS because I have to, not because I want to.

> > A self-submitted app from a GitHub repository that is not notable enough (under 50 stars).
>
> It seems it would be better if the app would be submitted NOT by Tigase team (self-submission inclusion)

That makes sense, but unless @joschi is a member of your team, that didn't seem to make a difference with his/her PR.

> It seems that if you want it submitted to Homebrew then it would be awesome to promote it more and encourage your friends, buddies and contacts to star it on GitHub. (We wouldn't mind doing it also for our other projects: [iOS SiskinIM](https://github.com/tigase/siskin-im/), [Tigase XMPP Server](https://github.com/tigase/tigase-server/), [Android StorkIM](https://github.com/tigase/stork))

Haha, maybe. There are very few users on my server, and they don't use MacOS. I'll see what I can do, though.

In the meantime, I may [create](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) a "[Tap](https://docs.brew.sh/Taps)" (basically an unofficial Homebrew supplement) and add Beagle to it, unless you would like to do so here.

Lastly, congratulations for making a good-looking, OMEMO-supporting MacOS XMPP client.

**Comment by joschi** [comment]
> That makes sense, but unless @joschi is a member of your team, that didn't seem to make a difference with his/her PR.

@michaelblyons I am not. 😉

@woj-tek Would it make sense for Tigase to maintain a custom tap for installing BeagleIM and maybe Tigase XMPP Server on macOS via Homebrew?
I'm happy to provide the cask for BeagleIM (the one from Homebrew/homebrew-cask#75450).

**Comment by woj-tek** [comment]
We could create and maintain Tap ourselves, though I fear that it could hinder future inclusion of Beagle in main hombrew repository (once it meets acceptance criteria) with the notion that "it already has a tap"

**Comment by woj-tek** [comment]
@joschi would you consider making PR to this repository: https://github.com/tigase/homebrew-tigase ? I wasn't sure that you saying "I'm happy to provide the cask for BeagleIM" implied that you were OK with I grabbing and adding it to the repository myself :-)

**Comment by michaelblyons** [comment]
I stole @joschi's, made a Tap, and bumped it to the latest. I can just transfer the repo to you. (You'll have to edit the README.md)

https://github.com/michaelblyons/homebrew-tigase

**Comment by woj-tek** [comment]
@michaelblyons ok, let's do it that way - I renamed the repository freeing namespace

**Comment by michaelblyons** [comment]
Ack! I can't do a transfer if I can't create repos in your org. 😞 Maybe rename yours back, HTTPS-clone mine, and push. (Yours should be canonical, not a fork 😉)

Otherwise, add me to the org and kick me out in ten minutes.

**Comment by michaelblyons** [comment]
Looks good!

**Comment by joschi** [comment]
@woj-tek Sorry for the mix up. I thought you would use the repository created by @michaelblyons, which included my original Homebrew formula, as a starting point.

Thanks both for taking care of this! 🎉

**Comment by woj-tek** [comment]
Thank you (both) for suggesting and contributing 👍

**Comment by michaelblyons** [comment]
Congrats on 50 stars.

**Comment by woj-tek** [comment]
I wonder if that would be enough to re-submit it. Though, I'd say that Beagle's own tap is working just fine.
