### ISSUE TITLE
Open Contact Window on startup

### ISSUE THREAD

**Issue by stefanathome** [tigase/beagle-im#15]
Hello,

As a replacement for iChat I#m using Beagle (3.6) and I’m very satisfied with it.
A small feature would improve my satisfaction…
When I start my Mac every day I have to click on the Beagle-app and hit Shift-2 to activate the contact-window.
I would please you to implement the feature that Beagle starts with all windows opened as when I shutdown the computer….
Or it would also be a solution if there is a setting in the preferences to define the windows which should be opened at startup

Tank a lot

Best regards
Stefan

**Comment by hantu85** [comment]
That should be solved in our latest beta builds
