### ISSUE TITLE
SVG version of the Beagle IM logo

### ISSUE THREAD

**Issue by sjehuda** [tigase/beagle-im#159]
Good day!

I would be glad to obtain an SVG version of the Beagle IM logo, in order to include it in the list of recommended XMPP client of FASI (an HTML invite page for XMPP.

See https://git.xmpp-it.net/sch/FASI/issues/1

**Comment by arthef** [comment]
@hantu85 could you please provide requested files?

**Comment by sjehuda** [comment]
In the meantime, I will use this SVG as a specific placeholder for Beagle.

```xml
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 100 100">
  <text y=".9em" font-size="80">🐶️</text>
</svg>
```

**Comment by hantu85** [comment]
I've added logo to the repository at https://github.com/tigase/beagle-im/blob/master/logo.svg

**Comment by sjehuda** [comment]
Thank you!

Beagle has been added to the selection!

https://git.xmpp-it.net/sch/FASI/commit/373b7b1f05d3f3c3b5cd4f3a17589db25a0bca2d#diff-909d22bde12503cc431c63cd8f8b527dad4d7753
