### ISSUE TITLE
Pop-up nick selector goes offscreen in fullscreen mode

### ISSUE THREAD

**Issue by ingoj** [tigase/beagle-im#18]
**Describe the bug**
When starting with @<nick> a popup selector appears. Unfortunately, when in fullscreen mode, the selection list goes offscreen, making it hard to select the correct nick

Example screenshot (typed: "@ W o" for Wojtek):

<img width="265" alt="Bildschirmfoto 2020-03-19 um 19 03 22" src="https://user-images.githubusercontent.com/18173881/77099726-b3ffd700-6a14-11ea-9932-0379b1775c0e.png">

**Comment by hantu85** [comment]
I'll report it to Apple as this completion list is macOS built-in feature.

**Comment by hantu85** [comment]
Reported using Feedback Assistant with report id FB7632479

**Comment by eevvoor** [comment]
any advances on this @hantu85 ?

**Comment by hantu85** [comment]
It was reported to Apple and I did not get any answer from them

**Comment by eevvoor** [comment]
Any workarounds possible?

**Comment by hantu85** [comment]
This should be fixed in 5.0
