### ISSUE TITLE
Can not send messages to non-OMEMO users

### ISSUE THREAD

**Issue by vitalyster** [tigase/beagle-im#19]
I got "There is no trusted device to send message to" when trying to send a message to contact without OMEMO.

**Expected behavior**
Message should be sent (maybe with warning or so)

**Desktop (please complete the following information):**
 - OS: latest macOS, latest Beagle IM from AppStore (Version 3.7.1 (79))

**Comment by hantu85** [comment]
You CAN send messages to users without OMEMO. Just disable OMEMO encryption in chat with a user who doesn’t have device with OMEMO support. Tap on the lock button in the chat window and switch to unlocked.

**Comment by vitalyster** [comment]
<img width="212" alt="Screenshot 2020-03-25 at 21 30 08" src="https://user-images.githubusercontent.com/1052407/77572363-e3fd1d80-6edf-11ea-8c0f-9362d6cbd5ce.png">
Icon in the right of input field is unlocked and inactive, icon in the right of error message is locked and click does not do anything

**Comment by hantu85** [comment]
The issue is then most lightly different. You have enabled OMEMO as default and you have a chat with someone who is not in your roster. To solve that, you can try to change default encryption to none and reopen that chat. 

We will try to improve this behavior in future version.

**Comment by vitalyster** [comment]
Contacts are in my roster (with "to" subscription)

**Comment by vitalyster** [comment]
Ok, switched to "none" encryption solved the problem (I'm not sure I did touch this before)

**Comment by hantu85** [comment]
By default, BeagleIM comes with optional OMEMO support which means that default encryption is set to NONE.
