### ISSUE TITLE
Chat window - support separate scroll areas for group chats and direct chats

### ISSUE THREAD

**Issue by ingoj** [tigase/beagle-im#22]
Currently BeagleIM has a combined scroll area for group chats and direct chats (plus from unknown). 

If you have joined many group chats, the direct chats will be moved out of sight and you will not be aware of new incoming personal chat messages. 

When there would be two independent scroll areas on the left for group chats and direct chats this would improve the situation significantly: the most active chats would be moved on top of the respective scroll areas and you would have new messages for both within your sight.

**Comment by arturhefczyc** [comment]
Hi,
Thank you for your comments. Yes, we agree, we noticed this issue as well and we have been discussing this for some time. We are looking at the best way to improve the UI.

**Comment by hantu85** [comment]
We have introduced a new chats list with merged "groupchats"/"channels" and "direct messages", that should solve scrolling issues.
