### ISSUE TITLE
Font Size Not Working

### ISSUE THREAD

**Issue by firekingsid** [tigase/beagle-im#23]
I love your product.
But there is no setting for the **hostname**(Connection Server) which all the other IM apps have.
Hope you add this feature asap.
Thanks.

**Comment by hantu85** [comment]
As already mentioned in a comment for SiskinIM, in most scenarios you should not be using server name or need to specify server name to connect to the XMPP server, see https://github.com/tigase/siskin-im/issues/23#issuecomment-604664615

**Comment by firekingsid** [comment]
But my boss has hosted the server on our local network.
```
192.168.1.225
```
So I need to point the server address and port.

**Comment by hantu85** [comment]
You can have DNS SRV entries resolving to local IP addresses, so there is still no need for setting custom server name.

**Comment by firekingsid** [comment]
Thanks. I resolved that.
But one more question.
How can I group the contacts?

**Comment by hantu85** [comment]
I suppose you are referring to the grouping of contacts in the contacts window. That is not supported.

**Comment by firekingsid** [comment]
Okay, then is this feature in your future roadmap or not in your next plans?

**Comment by hantu85** [comment]
It is not on the roadmap as we are trying to remove the requirement for people to use the contacts window and allow them to chat from the chats window.

**Comment by firekingsid** [comment]
I tried to make the font bigger or smaller, but it's not working.

**Comment by hantu85** [comment]
If you are referring to the top bar "Format" menu, then it is not working as it is not supported and that will be fixed by removal of that menu.

**Comment by firekingsid** [comment]
Oh no, can you please add that feature in the next release?
Font Size, or Zoom In & Out.

**Comment by hantu85** [comment]
The font size of all fonts within the application is correlated to the size of the system fonts used by macOS. We are not going to change that.

**Comment by firekingsid** [comment]
What about the avatar?

**Comment by hantu85** [comment]
Scales with resolution in the same way as font size
