### ISSUE TITLE
Client priorities

### ISSUE THREAD

**Issue by ergrlch** [tigase/beagle-im#27]
Im using beagle.im and siskin.im on my devices. When I receive messages on one device, I can't see them on others. My college who's built our server infrastructure told me, all clients would operate with the same priority. I myself can't find any way, to activate different priorities.. Is there any way to do that within beagle.im?

**Comment by hantu85** [comment]
No, there is no way to change priorities. In most cases messages sent to bare JID should be delivered to all connected resources which would solve the issue. Moreover our clients support message carbons which should deliver copies of messages to other resources.

Both of those features should be supported by XMPP server to achieve best results.
