### ISSUE TITLE
Change section header "Groupchats" to "Group chats"

### ISSUE THREAD

**Issue by ableyjoe** [tigase/beagle-im#28]
**Describe the bug**
The Chats window includes a section header in the left, purple section called "Groupchats".

This is a bit jarring to a native English speaker; it would be more usual to make that "Group chats" with a space (so, two words).

I realise this is a very minor issue and that possibly I may have severe personality problems for this to bother me as much as it does.

**To Reproduce**
1. Open Chats window
2. Align face such that Chats window is in front of face
3. Open eyes

**Expected behavior**
Change section heading from "Groupchats" to "Group chats".

**Screenshots**
![Screenshot 2020-04-23 at 12 50 51](https://user-images.githubusercontent.com/6536726/80126440-1b9fc980-8561-11ea-9d21-ae26cab270a3.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.4

**Additional context**
None.

**Comment by hantu85** [comment]
In the beta build of version 4.0, it is already renamed to `Channels`.
