### ISSUE TITLE
Can't receive OMEMO file from self.

### ISSUE THREAD

**Issue by michaelblyons** [tigase/beagle-im#30]
### Describe the bug

I sometimes use XMPP to send a link or text to myself between devices. ~(This works in Beagle, but has small weird thing, where I am listed as "From unknown" in sidebar.)~ I tried doing this with sending a file as well, but I always get an error message:

> I sent you an OMEMO encrypted message, but your client doesn't seem to support that. Find more information on https://conversations.im/omemo

### To Reproduce

1. Sign into Beagle on MacOS (Enable OMEMO)
2. Sign into Conversations.im on Android as same user (Enable OMEMO)
3. In Conversations.im, share file to a chat with self
4. In Beagle, attempt to view file
5. See message

### Expected behavior

- I can download files in chats with myself just like I can with other people's chats.
- ~Ideally, I am not listed as "From unknown" in the sidebar.~

### Screenshots

<img width="374" alt="Screen Shot 2020-05-02 at 4 21 44 PM" src="https://user-images.githubusercontent.com/2701605/80891303-ac3d7e80-8cb2-11ea-92c5-e286dea3f410.png">

### Desktop:

 - OS: 10.15.4 (19E287)
 - Browser: N/A
 - Version: Version 3.7.1 (79)

### Smartphone:

 - Device: Google Pixel 2a
 - OS: Android... 10?
 - Browser: N/A
 - Version: Conversations.im (F-Droid edition: v2.7.1+FCR)

**Comment by hantu85** [comment]
Were you able to successfully receive a message/file sent to self from Conversations on another client? ie. another Convesations? or any other OMEMO compatible XMPP client?

I'm asking about that, bacause main reason why people cannot see their messages are actually releated to the fact that those messages are not encrypted for particular device.

As for being listed in "From unknown" section, the behavior is correct. If the sender of a message is not in your contacts list (roster) then it listed in "From unknown" section.

**Comment by michaelblyons** [comment]
> Were you able to successfully receive a message/file sent to self from Conversations on another client? ie. another Convesations? or any other OMEMO compatible XMPP client?

I will check this. I have a Gnome client somewhere that I sometimes use.

> As for being listed in "From unknown" section, the behavior is correct. If the sender of a message is not in your contacts list (roster) then it listed in "From unknown" section.

Ah, I see. I could not find a way to add a contact in the "From unknown" section to my contacts list (only to block them). Now that I have added myself from the real "Contacts" window, I show up as expected.

**Comment by michaelblyons** [comment]
Sorry it took so long. I've now tried it with Conversations -> Gajim. It worked. Then I discovered that the file was also available on Beagle (though not past ones), even though I still got that OMEMO fish from the original screenshot.
