### ISSUE TITLE
iPhone Support

### ISSUE THREAD

**Issue by myzinsky** [tigase/beagle-im#31]
Are you planning an iPhone Support?

**Comment by hantu85** [comment]
BeagleIM is macOS only. For iOS (iPhone and iPad) we provide SiskinIM. See https://siskin.im

**Comment by myzinsky** [comment]
Thank you so much for the hint. Just curiosity: why do you have two different names for these apps? From a corporate identity point of view it would make sense to have the same name and logo?

**Comment by hantu85** [comment]
I'm tired of explaining that, but those are two separate apps and may have a different look and different features, so due to that they have separate names. Also, it is easier to know which client or its behavior is discussed.
