### ISSUE TITLE
Closing chat tab results in no X in next chat tab

### ISSUE THREAD

**Issue by ingoj** [tigase/beagle-im#32]
Well, not sure if bug or feature, but when closing a chat tab (tested in fullscreen mode) has the effect that the next chat tab that moves up is missing the X. The X only appears when you move the mouse cursor around to another tab and then back again... 
Using beta build b94 at the moment. 

This video shows the problem (link valid until Aug. 31st.): https://silverhaze.org/s/D3x9fwY2nofmoo3

**Comment by hantu85** [comment]
It is known behavior and I see it as a feature, as even if I would double click I will not close the second chat which just moved up after I've closed previous chat.

**Comment by ingoj** [comment]
Yeah, I think as well it's more like a good feature. Only issue is that I couldn't reproduce it when not in full screen mode. Maybe check and make it a consistant... 

You may want to close this issue then. Thx!
