### ISSUE TITLE
Beagle IM version 3.4 

### ISSUE THREAD

**Issue by imrsic** [tigase/beagle-im#33]
Where can i download older version of Beagle IM (3.4, 3.5) for mac os? Currently on apple store available app is 3.7, which is compatible with OS 10.14 and above. I'm running 10.13, and can't go any higher with this device.

Thanks

**Comment by hantu85** [comment]
You can check the [Releases](https://github.com/tigase/beagle-im/releases) section. There are all versions that can be downloaded. Please keep in mind that older versions are not supported by us anymore as new versions have fixes and improvements for issues reported in older versions.

**Comment by imrsic** [comment]
Thanks Andrzey,

Looks like 3.4 is not compatible with OS 10.13 either. So I tried 3.0, but only source code is included, no installer.

Ivo

**Comment by hantu85** [comment]
That means that we do not have any build of version 3.0 and 10.13 is not supported any more.
