### ISSUE TITLE
Unable to build from source in Xcode due to JingleModule errors

### ISSUE THREAD

**Issue by f055** [tigase/beagle-im#34]
**Describe the bug**
I am trying to build BeagleIM in Xcode using branch mix-new_chatslist but I encounter a flood of errors related to JingleModule and JingleManager.

**To Reproduce**
1. Open "BeagleIM.xcodeproj" and change "Team" in "Signing & Capabilities" to my own
2. Add "OpenSSL.xcodeproj" from github.com/krzyzanowskim/openssl and build it for macOS
3. Build "BeagleIM" and see dozens of errors starting with: "BeagleIM/voip/JingleManager.swift:30:72: Type 'JingleModule' has no member 'JingleMessageInitiationEvent'" etc.

I tested it's possible to build BeagleIM by going a few commits back where JingleModule was not an issue, but I would like to be able to compile the latest state.

**Comment by hantu85** [comment]
Are you using TigaseSwift `mix` branch? Most likely, you will need to refresh (pull) new commits from TigaseSwift

**Comment by f055** [comment]
I'm using `mix-new_chatslist`. Thanks for quick reply, I'll try pulling within Xcode.

**Comment by hantu85** [comment]
I'm asking about TigaseSwift branch, not BeagleIM branch!

**Comment by f055** [comment]
Ah! Sorry, I got mixed. Xcode Swift Package Dependencies shows me I'm using TigaseSwift mix.

**Comment by hantu85** [comment]
Try refreshing TigaseSwift package, it most likely has old vesion cached from `mix` branch.

**Comment by f055** [comment]
Build Succeeded! Thanks a lot 👍 I did File > Swift Packages > Update to Latest Package Versions
