### ISSUE TITLE
Suggestion for improved app icons for BeagleIM and other Tigase clients

### ISSUE THREAD

**Issue by f055** [tigase/beagle-im#35]
**Is your feature request related to a problem? Please describe.**
Current app icons of BeagleIM, while showing a really nice dog, seem more like a placeholder than a proper icon that visually fits into the macOS ecosystem. The same applies to SiskinIM and more-less Stork. If you consider it, I propose to provide the below icons by the means of a Pull Request in each repo. No strings attached and no pressure. If you don't like it, disregard it.

![icons](https://user-images.githubusercontent.com/53429/85117919-e42b6180-b21f-11ea-8495-88998f14e3bb.png)

**Comment by hantu85** [comment]
Thank you for the suggestion, but we do not consider changes to our app icons at this time.
