### ISSUE TITLE
Own avatar appears for other contacts and MUCs

### ISSUE THREAD

**Issue by ingoj** [tigase/beagle-im#36]
After uploading my avatar pic it happens from time to time that the same pic does appear as the avatar for other people as well as for MUCs: 

<img width="118" alt="Bildschirmfoto 2020-07-05 um 16 38 01" src="https://user-images.githubusercontent.com/18173881/86961849-34804a00-c162-11ea-83a0-ec5a31ddca7c.png">
<img width="50" alt="Bildschirmfoto 2020-07-05 um 16 38 32" src="https://user-images.githubusercontent.com/18173881/86961860-36e2a400-c162-11ea-9458-e4fcd4b9c45f.png">

My impression is that this happens mostly when adding a new contact or MUC that has no own avatar pic uploaded, but not every time. So I guess it's hard to track this issue down...

**Comment by woj-tek** [comment]
Thank you, we will look into it.

#beagleim-258

**Comment by hantu85** [comment]
I've not found anything in the logs, but I was able to track the possible issue to the case when your client would receive `<presence/>` of type `error`, ie. if remote entity sends it back (ie. with `service-unavailable`). That would store a wrong entry in the database and would not be updated as remote entity does not have an avatar set. 

Fix will be released in the next build, however, it will not be able to fix entries in the database and dropping all info about avatars is not a good idea for most of the users.

**Comment by ingoj** [comment]
So, I guess the "fix" for existing issues would be to change avatar pics back and forth, right?
