### ISSUE TITLE
XEP-0308 - Last Message Correction

### ISSUE THREAD

**Issue by ingoj** [tigase/beagle-im#38]
Hi!

Does Beagle/Siskin support Last Message Correction as stated in XEP-0308?
In some MUCs it's quite common that I see such things: 

<img width="1131" alt="Bildschirmfoto 2020-07-10 um 12 55 19" src="https://user-images.githubusercontent.com/18173881/87147482-fe031600-c2ac-11ea-899f-05a693bf8e9f.png">

Maybe it's also a different XEP that's relevant here... :)

**Comment by hantu85** [comment]
No, it is not supported, but it will be in the next release.

**Comment by ingoj** [comment]
Oh my.... can't wait for the next release... so many new things to come :-) 👍

**Comment by hantu85** [comment]
I'm closing the issue as this feature is now supported in 4.0b99
