### ISSUE TITLE
Different font formatting in sidebar and chat window

### ISSUE THREAD

**Issue by ingoj** [tigase/beagle-im#39]
Hi!

There seems to be a formatting issue in the sidebar when there are special chars occurring in chat window. 
See screenshots: 
![Bildschirmfoto 2020-07-19 um 21 57 32](https://user-images.githubusercontent.com/18173881/87883944-2d332900-ca0b-11ea-8f42-ddde4465f40a.png)
![Bildschirmfoto 2020-07-19 um 21 57 44](https://user-images.githubusercontent.com/18173881/87883948-32907380-ca0b-11ea-8687-2636b08b9af3.png)
![Bildschirmfoto 2020-07-19 um 21 58 02](https://user-images.githubusercontent.com/18173881/87883951-3623fa80-ca0b-11ea-9762-f105062e6089.png)

Text is: 
```
I do this:
`git pull && ./autogen.sh && make update && ./configure --enable-new-sql-schema --enable-pgsql --enable-sip --enable-stun --enable-user=ejabberd --enable-group=ejabberd --prefix=/usr/local && make -j $(nproc)`
_(adapt the configure part to your setup)_
```

Sometimes, depending on the special chars, the text in sidebars is not well readable, like very condensed and italic or similar like that.

**Comment by hantu85** [comment]
That is something (text formatting) which was improved recently but new build is not ready for testing.

**Comment by hantu85** [comment]
Version 4.0b99 should fix that.
