### ISSUE TITLE
Turn off "User Session Not Found" notification

### ISSUE THREAD

**Issue by michaelblyons** [tigase/beagle-im#44]
I suspect I'm just missing some UI setting. I'd like to turn off the 

```
------
User session not found
```

notifications. At _least_ stop showing a new message indicator for them. I'll be chatting with my wife, and then some time after we finish, I get a notification icon `(1)`. I think she has sent me a new message, but instead Beagle is just telling me that she's disconnected.

**Comment by hantu85** [comment]
This is not a "notification" but actual error message sent by the server of the recipient of your messages. Normally, those servers should store message in the offline storage and not send errors back.

This is actually the issue of the server which you are using and you will need to fix it on the server side.
