### ISSUE TITLE
Hard crash when viewing messages (macOS 11.0 b)

### ISSUE THREAD

**Issue by shibacomputer** [tigase/beagle-im#47]
**Describe the bug**
Hard crash when viewing a received message due to unhandled permissions error on macOS 11.0b (20A5354i)

**To Reproduce**
1. Install Beagle
2. Create an account and receive a message from someone
3. Click the message
4. Immediate hard crash

**Expected behavior**
See the message

**Desktop (please complete the following information):**
 - OS: macOS 11.0b (20A5354i)
 - Version 4.0

**Additional context**
Here's the relevant part from the Problem Report generated by Apple:

```
Process:               BeagleIM [3387]
Path:                  /Applications/BeagleIM.app/Contents/MacOS/BeagleIM
Identifier:            org.tigase.messenger.BeagleIM
Version:               4.0 (103)
App Item ID:           1445349494
App External ID:       837575887
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           BeagleIM [3387]
User ID:               501

Date/Time:             2020-09-05 15:32:23.025 +0200
OS Version:            Mac OS X 10.16 (20A5354i)
Report Version:        12
Bridge OS Version:     5.0 (18P50358b)
Anonymous UUID:        338EB067-441C-5267-6EF3-151D2A5F0309

Sleep/Wake UUID:       1C278FD8-2249-4C9D-A4FA-A8A8F108E61E

Time Awake Since Boot: 2900 seconds
Time Since Wake:       1000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [3387]

Application Specific Information:
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “org.tigase.messenger.BeagleIM” in the folder “Application Scripts”." UserInfo={NSFilePath=/Users/shibco/Library/Application Scripts/org.tigase.messenger.BeagleIM, NSUnderlyingError=0x6000035c5980 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}: file /Users/andrzej/Development/xcode/BeagleIM/BeagleIM/utils/ScriptsManager.swift, line 35
```

**Comment by shibacomputer** [comment]
This can be fixed by manually navigating to ~/Library/Application Scripts/ and creating the "org.tigase.messenger.BeagleIM" directory.

**Comment by hantu85** [comment]
BeagleIM is not macOS 11 ready. We will try to solve the issue in the upcoming version, however it was not mentioned anywhere (or at least I was not able to find any mentions of permission change). Those was the only directory to which access to the app was granted out of the box just for scripting purposes. I suppose that scripting will no longer work and we will need to disable it.

**Comment by shibacomputer** [comment]
Apple's changes on macOS seem more and more breaking with every release. Thanks for your patience with this hilarious company.
