### ISSUE TITLE
Could not retrive current version from the server.

### ISSUE THREAD

**Issue by schittler** [tigase/beagle-im#5]
**Describe the bug**
When no profile is returned - e.g. on a fresh Prosody account, the "Personal" tab will error with

> **Could not retrive current version from the server.**
> Server returned an error: undefined_condition

**To Reproduce**
1. Spin up Prosody.
2. Create a new account from CLI.
3. Login with BeagleIM
4. Attempt to edit your own profile

**Expected behavior**
Can submit vCard without one set up prior.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G95)

**Comment by hantu85** [comment]
This issue should be fixed in the next version of BeagleIM.
