### ISSUE TITLE
Support for XEP-0245: /me command

### ISSUE THREAD

**Issue by mwild1** [tigase/beagle-im#50]
**Is your feature request related to a problem? Please describe.**

- XEP-0245: /me command is in the compliance suite and not implemented
- Sometimes people using other clients write `/me goes to the shops` and it looks strange
- Although archaic, `/me` is also supported by a number of other messaging platforms

**Describe the solution you'd like**
Implementation of XEP-0245 in Beagle and Siskin.

**Describe alternatives you've considered**
I considered the alternative of it not being implemented, this made me feel sad.

**Additional context**
We're discussing recommending Beagle IM as the macOS client for IETF virtual MUC meetings. It would be good to ensure continuity of features from previously recommended clients for macOS (Adium) and interoperability with other XMPP clients that other meeting attendees may be using on other platforms.

**Comment by hantu85** [comment]
Feature will be available in next beta build od version 4.1

**Comment by michaelblyons** [comment]
Can be closed?
