### ISSUE TITLE
OTR support

### ISSUE THREAD

**Issue by Minoru** [tigase/beagle-im#51]
**Is your feature request related to a problem? Please describe.**
Lack of support for [OTR](https://otr.cypherpunks.ca/) makes it impossible for Beagle to establish encrypted chats with clients that don't support OMEMO, e.g. mcabber.

**Describe the solution you'd like**
I'd like for Beagle to support OTR.

**Describe alternatives you've considered**
It seems like the only alternative is to ask all the contacts to upgrade to a client that supports OMEMO. That's hardly workable.

**Comment by woj-tek** [comment]
Relevant XEPs:
* https://xmpp.org/extensions/xep-0378.html
* https://xmpp.org/extensions/xep-0364.html

I wouldn't say that implementing this would be high on our to-do list unfortunately.

**Comment by hantu85** [comment]
I'm not convinced to implement support for OTR as we try to have a feature parity with iOS client which is usually offline and woke up by push notifications. With OTR and `no-premanent-store` and `no-copy` requirement from the XEP-364 it looks like adding a support for OTR to iOS would be impossible (or at least very tricky).

**Comment by Minoru** [comment]
Sounds reasonable. Thank you! I'll close the issue then.
