### ISSUE TITLE
UX: Jump direct to 'Add XMPP account' on new installation

### ISSUE THREAD

**Issue by mwild1** [tigase/beagle-im#54]
**Is your feature request related to a problem? Please describe.**

On first install, Beagle 4.0 (103) helpfully prompts the user to add a new account. If the user selects 'Yes' then it opens an account dialog, but none of the fields are editable, and the 'Change password' dialog can be opened but doesn't do anything.

The secret is to click the '+' button under the account list. But this is not obvious.

**Describe the solution you'd like**

Potential improvements:

- Automatically opening the 'Add XMPP account' dialog if the user clicked 'yes' in the first prompt, or maybe always if the account list is empty.
- Disable form controls that don't work properly (e.g. password change button)
- If the account list is empty, show a hint or placeholder instructing the user to click '+' to add one.

**Comment by arturhefczyc** [comment]
+1 from me on all points.

These are little usability improvements which really make it easier for new comers to start using the app.

**Comment by hantu85** [comment]
I've went with simply solution and "slightly" modified suggested improvements.

In the next build if BeagleIM will not find any XMPP accounts, it will ask user if he wants to add an account and show him a preferences with accounts like (just like now). 

However, accounts list dialog is now modified to block fields which should not be accessible without any accounts and if no accounts are found `Add XMPP account` will always be opened when accounts list is being presented (in preferences).

This way we have a hint (very strong one as we are opening a window) and it automatically works with our onboarding dialog.
