### ISSUE TITLE
VCard edit not available - button greyed out

### ISSUE THREAD

**Issue by arturhefczyc** [tigase/beagle-im#55]
**Describe the bug**
For multiple accounts setup, if there is vcard retrieving problem for one account, the edit button is greyed out and disabled for all accounts.

**To Reproduce**
1. Go to BeagleIM preferences
2. Click on Accounts
3. If you have multiple accounts, make one of them offline
4. Click on refresh or edit vcard for this offline account
5. The edit button is now disabled for all accounts.

Even refresh vcard for any working/online account does not bring edit back. The only way to have edit working is to restart the app.

**Expected behavior**
The edit button should be disabled only for affected account.

**Comment by hantu85** [comment]
The issue was fixed and I've added code which will adjust "state" of the buttons based on the fact whether account is connected or not.

**Comment by arturhefczyc** [comment]
Fixed for me, thank you.
