### ISSUE TITLE
Awkward process to enter correct password

### ISSUE THREAD

**Issue by arturhefczyc** [tigase/beagle-im#56]
**Is your feature request related to a problem? Please describe.**
Currently, when adding a new account and entering incorrect password, correcting mistake is very laborious.
Accounts gets deactivated, then user has to click on Change password and provide the correct password 2 times, then click to activate account.

**Describe the solution you'd like**
When incorrect password is detected, the app should provide simple way, a form with a single password input line to provide a correct password.

**Comment by hantu85** [comment]
`Change password` dialog was simplified when account is not connected (ie. due to invalid password. 

Additionally, "onboarding" process was improved by checking account details upon clicking on `Log in` button but before saving account details. That should make this process more user-friendly.

**Comment by arturhefczyc** [comment]
Works great, thank you.
