### ISSUE TITLE
Password Not Correct

### ISSUE THREAD

**Issue by myzinsky** [tigase/beagle-im#57]
**Describe the bug**
When I want to login into a group chat that is password protected and on an external server. Beagle complains that the password is wrong. I'm certain that I have the correct password. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1970554/95741663-edd54b00-0c8e-11eb-8483-4d561d047e17.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2)

**Comment by hantu85** [comment]
Thank you for reporting the issue. I confirm that there is an issue and fix for it will be in the next beta build of BeagleIM and in then next version of BeagleIM.
