### ISSUE TITLE
A copy link to files that are uploaded option

### ISSUE THREAD

**Issue by Austcool-Walker** [tigase/beagle-im#61]
**Is your feature request related to a problem? Please describe.**
Yes the feature that other applications like conversations.im for android have is the ability to copy the urls to files uploaded on the server

**Describe the solution you'd like**
I would like the ability to right click in chat and copy file url to clipboard so I can past it in a web browser to download the files that are uploaded to the xmpp servers

**Describe alternatives you've considered**
I've considered using other web clients like movim but they aren't exactly the best option for my needs and are heavy in browser

**Additional context**
examples of copied urls
```
https://www.xmpp.jp/upload/9c10895086c29ea0c852ba205fa25d8e580dacb3/vXjuG01vzsSyOtY4Uc2sj9z4keE4QeXFFnV8pAMp/Screenshot_20201101-171048_Conversations.jpg
https://www.xmpp.jp/upload/9c10895086c29ea0c852ba205fa25d8e580dacb3/EAKUcfoAGTUqzK5INMVLtOcdqt2maEGO11VDlVSr/Screenshot_20201101-171003_Conversations.jpg
```
![Screenshot_20201101-171048_Conversations](https://user-images.githubusercontent.com/61804916/97816801-cb1ecc80-1c65-11eb-908f-db13fae15416.jpg)
![Screenshot_20201101-171003_Conversations](https://user-images.githubusercontent.com/61804916/97816811-f3a6c680-1c65-11eb-8258-70d1a1d492e3.jpg)

**Comment by hantu85** [comment]
BeagleIM is fully capable of downloading files on its own. In this case copying original URL is a waste of time and transfer as the file is already on your drive. Just use `gear` button next to the file details to access additional action like `Open`, `Copy`, `Share`.
