### ISSUE TITLE
OMEMO messages sent from Monal are not decrypted

### ISSUE THREAD

**Issue by foss-** [tigase/beagle-im#64]
**Describe the bug**
Sending an OMEMO message from [Monal alpha](https://www.eightysoft.de/monal/) or the current [iOS beta](https://testflight.apple.com/join/RjIlyvqa) are not decrypted in BeagleIM (or SiskinIM) for myself.

The recipient is able to decrypt just fine. But for my own encrypted messages sent from Monal I see `Message decryption failed!`

**To Reproduce**
1. open monal
1. open beagle both with same xmpp account
1. create a 1:1 chat with a contact
1. enable OMEMO
1. send encrypted message from monal alpha or beta

**Expected behavior**
Messages should show and be decrypted in Beagle 1:1 chat view.

**Current behavior**
Message decryption failed! message

**Screenshots**
<img width="191" alt="failed" src="https://user-images.githubusercontent.com/5708172/100553227-f4467300-328c-11eb-8586-31b3797b60cc.png">

**Desktop:**
 - OS: macOS 10.15.7
 - Version 4.1 (110)
- Monal alpha / beta builds (links above)

**Additional Info**
Talked to Monal devs and they mentioned that this could be the result of issues in regards to key transport element from a message stanza not supported or correctly implemented in Beagle / Siskin.

**Comment by ritzmann** [comment]
Did you test with any other XMPP clients than Beagle? Monal has been a non-functional heap of bugs since its inception and I would first go looking for bugs there.

**Comment by foss-** [comment]
Same messages decrypt as expected in converse js. Other clients worked as well, would have to check with non-Apple users which exact clients they use.

**Comment by foss-** [comment]
Fixed on Monal side: https://github.com/tmolitor-stud-tu/Monal/commit/79d268bc8d8a790ce01dc775ba1f481f05282b0c
closing
