### ISSUE TITLE
Beagle b111 - displaying images not working properly in MUC (double entry, one as loading)

### ISSUE THREAD

**Issue by ingoj** [tigase/beagle-im#70]
After testing b112 and going back to b111 because of the hangs (not responding) in MUCs, there is another issue in b111, maybe also in b112. 

When there is a photo being uploaded to a MUC it happens that it is listed twice: once correct as a photo and second as a loading photo: 
![Bildschirmfoto 2020-12-25 um 11 32 42](https://user-images.githubusercontent.com/18173881/103132555-5a17f600-46a5-11eb-8106-76591a15c2f5.png)

When you switch forth and back to another MUC/chat, the second "loading" photo will be gone and everything is ok: 
![Bildschirmfoto 2020-12-25 um 11 36 53](https://user-images.githubusercontent.com/18173881/103132587-82075980-46a5-11eb-97c9-bbed1f694a72.png)

**Comment by hantu85** [comment]
This issue was already fixed in b112 in commit 5f80d42ca4383bb4cbf6436d13896fd60af74c64
Please do not report issues without confirming that they exist in the last build of the same version of the app or at least reviewing commit log for the last version.
