### ISSUE TITLE
Apple Silicon M1 support

### ISSUE THREAD

**Issue by SharkyRawr** [tigase/beagle-im#72]
It would be nice to have an apple native build for the new apple silicon arm64 platform.  
I tried to build it myself with Xcode but ran in to issues because of missing frameworks:

```
beagle-im % xcodebuild
objc[23373]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1ff88b8f0) and ?? (0x1149942b8). One of the two will be used. Which one is undefined.
objc[23373]: Class AMSupportURLSession is implemented in both ?? (0x1ff88b940) and ?? (0x114994308). One of the two will be used. Which one is undefined.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

Resolve Package Graph

Fetching https://github.com/tigase/tigase-sqlite3.swift.git

xcodebuild: error: Could not resolve package dependencies:
  The remote repository could not be accessed. Make sure a valid repository exists at the specified location and that the correct credentials have been supplied.
```
https://github.com/tigase/tigase-sqlite3 appears to be completely gone?

**Comment by hantu85** [comment]
M1 support will be added at some point. Currently it is not a high priority on our todo list as BeagleIM does not use a lot of a CPU so benefit of a support for native M1 will be small to none.

**Comment by SharkyRawr** [comment]
What about the tigase-sqlite3 repo? Is there a replacement?

**Comment by hantu85** [comment]
No, you are trying to build `master` branch which contains development version of BeagleIM which uses some new frameworks which we will make public when they are ready and stable.

If you wish to build BeagleIM manually, I would suggest to go back to version tagged with `4.1`

**Comment by vitalyster** [comment]
Still an issue, please reopen to allow people be notified when it will be ready
