### ISSUE TITLE
The encryption icon is not visible 

### ISSUE THREAD

**Issue by leoblum** [tigase/beagle-im#73]
**Describe the bug**
The Lock icon which enable / disable encryption for specific chat window is not visible, but when I click in icon area context menu of encryption settings is showed and I can toggle encryption settings.

**To Reproduce**
I don't know. I just does not see this icon. I tried to reinstall app with `brew reinstall --cask beagleim` and I tried to move and resize application window – the icon is not visible to me.

**Expected behavior**
The Lock icon is visible right of message input field.

**Screenshots**
https://habrastorage.org/webt/9e/vr/f5/9evrf58vy5ljuxlh7ttpfa4zpke.png

**Desktop (please complete the following information):**
 - OS: MacOS 11.1
 - Browser Chrome
 - App Version 4.1
 
**Additional context**
The app was installed by brew cask.

**Comment by hantu85** [comment]
Works just fine with macOS 10.15.7 in 5.0 (beta) and in 4.1 (stable). However, I can confirm that it fails to work with macOS 11.1  - most likely an issue in macOS or Apple changed something again..

**Comment by vain90** [comment]
I have the same problem. Is there any news on this?
MacOS 11.2.1
BeagleIM 4.1 (from AppStore)

![Bildschirmfoto 2021-04-20 um 12 54 15](https://user-images.githubusercontent.com/11925757/115384603-85d06600-a1d7-11eb-8e88-7feb5360d0ea.jpg)

**Comment by hantu85** [comment]
As it was already mentioned by me, it is fixed in beta build and will be fixed in the AppStore when new version will be released.
