### ISSUE TITLE
Automatically create direct message dialogue when initiating or receiving a direct message

### ISSUE THREAD

**Issue by Poorchop** [tigase/beagle-im#75]
**Is your feature request related to a problem? Please describe.**
The handling of direct messages is a bit cumbersome right now. When receiving a direct message from someone in a MUC, it just shows up like any other message in the room but with an indication that it's a private message. To respond, the user must open the user list, right click on the other user, and select the option to send a private message in response.

**Describe the solution you'd like**
When receiving or sending a private message, a new dialogue should be automatically opened under the "direct messages" category in the channel list. This similar to how incoming PMs or `/query` works in some IRC clients.

**Describe alternatives you've considered**
The alternative is to just keep right-clicking the name of the user to whom I want to PM every single time that I want to send a private message. As far as I can tell, Beagle doesn't display the full XMPP address of users anywhere so I'm not even sure how to initiate a direct message in a new dialogue with someone in the same MUC.

**Additional context**
Great client, thanks for all of the work that has gone into it.

**Comment by hantu85** [comment]
We most likely will not create a separate chat for private conversations within MUC rooms. In most cases, those are just simple message exchanges and you are losing the context of the conversations from the MUC room (you do not see previous messages which could be also important).

In version 5.0, if you right-click (?) on the message on which you want to answer in the context menu you will find `Reply with PM` which will allow you to easily (without looking at the user's list) send a direct response without losing the context of the conversation in the room.

As for not showing JID of room members, in most cases, real JID is not available and messages are forwarded by the MUC room, so it is not possible to have a conversation this way with someone if either you or him are not in the room. Having those conversations separate would make it difficult to manage and could be for a first-time users confusing.

**Comment by Poorchop** [comment]
Thanks for clarifying. Good points - your explanation makes sense. I guess a simple context menu addition would be good enough in order to eliminate the need to go through the user list. Thanks.
