### ISSUE TITLE
Local file disappears when I send it

### ISSUE THREAD

**Issue by achempion** [tigase/beagle-im#76]
**Describe the bug**
Local file disappears when I send it to anyone from my contact list

**To Reproduce**
Open 1-to-1 chat, click "+" button, select a file. File sent successfully but you no longer have this file locally.

**Expected behavior**
My file stays with me.

**Desktop (please complete the following information):**
 - OS: macOS 11.0.1
 - BeagleIM Version 4.1 (110)

**Comment by hantu85** [comment]
This issue is already fixed in the source code ffe8ed019e84cfe77c8fc1a292baebe19cc1b274  and will be part of BeagleIM 5.0.
