### ISSUE TITLE
BeagleIM 3.4/3.5 crashing in Mojave with 2020-001 macOS secupdate installed?

### ISSUE THREAD

**Issue by LTC59** [tigase/beagle-im#8]
Hello!

We have some trouble with BeagleIM and the Openfire server we use at least since we updated.

We hade some chat-rooms disappearing in Openfire. They appeared to BeagleIM as "locked".
Don't know if anyone tried removing (the "static" / on the server setup) chat-rooms from BeagleIM (you can remove them using the X and add them again without trouble now) but maybe not with the other built-in "remove" method - I didn't try that.

After setting the missing chat-rooms up again we can see/use the chat-rooms again but BeagleIM quits frequently when sending a message to a chat-room. After starting BeagleIM again the message looks sent (I didn't verify/try this).

We have a very low degree of security in use - we only use it on the LAN.

Any suggestions or "fixed" newer version of BeagleIM "in the works"?

Best regards

**Comment by hantu85** [comment]
I'm not sure what the actual issue with MUC rooms and removing them is in the case of Openfire. BeagleIM just leaves the room on pressing the `X`.  (so this will not remove the room).  Room removal is available for room administrators in `Configure` item available in room context menu (actions button on top).

As for "crashing"/"exiting" of BeagleIM, we are aware of Mojave related issues as the app is misbehaving on Mojave while working perfectly fine on Catalina. We are now looking for the actual cause of the issues and some workaround as those issues are Mojave specific.

**Comment by hantu85** [comment]
As there is no follow up and current version of BeagleIM is stable on macOS Catalina I'm closing this issue.
