### ISSUE TITLE
Beagle b117 - removing account from application does not work

### ISSUE THREAD

**Issue by ingoj** [tigase/beagle-im#81]
See the video of trying to remove the configured account from BeagleIM (it's already deleted on server)... 

https://user-images.githubusercontent.com/18173881/112728768-20b38880-8f29-11eb-914c-fc7d73e2a2f8.mp4

(If video cannot be displayed, here's an alternative link valid until 2021-04-30: https://silverhaze.org/s/WgjWFfE6XgMZn3x )

**Comment by hantu85** [comment]
Are you using any other XMPP clients? ie. Psi or Psi+? recently I've seen a lot of issues related to XMPP account stored in Keychain and interaction between Psi/Psi+ and BeagleIM (basically Psi/Psi+ was taking over ownership of the account credentials stored in Keychain)

**Comment by ingoj** [comment]
Nope, not actively using anything beside Beagle on this Mac. From time to time I test Monal as well... is there anything I could spot in system console logs when I try to remove that account?

**Comment by hantu85** [comment]
Not really, it just fails. If you want to "remove" the account by hand, you could try to remove entry for this XMPP account (when BeagleIM is not running) from Keychain.

**Comment by ingoj** [comment]
Yep, that did the trick... but that's not very intuitive, of course. Maybe you can check if the removal worked and if not, give the user a popup information windows to delete that account in the Keychain? This would be a workaround until the real issue is fixed at least...

**Comment by hantu85** [comment]
I'm going to check that tomorrow, just wanted to give you a hint on what to do with that today.

**Comment by hantu85** [comment]
This should be fixed in the next beta build
