### ISSUE TITLE
When a file is shared, the local file is deleted

### ISSUE THREAD

**Issue by iXo** [tigase/beagle-im#82]
**Describe the bug**
Use the "+" button, select a file, it is shared, then it is deleted from the local drive.

**To Reproduce**
1. Go to MUC
2. Click on '+'
3. Select a file
4. The file is sent
5. The file is also deleted from the hard drive

**Expected behavior**
The file must be left intact

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Cataline 10.15.7
 - Version 4.1 (110)

**Comment by hantu85** [comment]
This issue was already reported on the support forum (xmpp:tigase@muc.tigase.org) and is fixed in the latest beta build of 5.0
