### ISSUE TITLE
"/me" action is showing different lines in b127

### ISSUE THREAD

**Issue by ingoj** [tigase/beagle-im#84]
Today I realized that the message preview in the sidebar shows a different line than the main chat window when using "/me" actions. While my nick was correctly shown in the chat window, the nick of my chat partner was falsely shown in the message preview in the side bar.

![Bildschirmfoto 2021-06-07 um 19 14 10](https://user-images.githubusercontent.com/18173881/121062336-3a910780-c7c5-11eb-9ae1-48d79d3bff4e.png)

I don't think this is correct. ;-) 

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Version: Beagle beta b127

**Comment by hantu85** [comment]
Thank you for reporting this issue. Fix will be included in the next build.
