### ISSUE TITLE
Docs update request

### ISSUE THREAD

**Issue by rdravi110** [tigase/beagle-im#85]
At this link https://github.com/tigase/beagle-im , the command to download the Beagle IM is given as:

```
brew tap tigase/tigase
brew cask install beagleim
```
This command returns the following error in latest version of Mac OS.

`Error: Unknown command: cask`

I entered the following command which worked and download Beagle IM in my system:
```
brew tap tigase/tigase
brew install --cask beagleim
```
Source: https://github.com/Homebrew/discussions/discussions/902#discussioncomment-398348

So I request you to update the docs.

**Comment by woj-tek** [comment]
Thank you for bringing that to our attention. Fixed.
