### ISSUE TITLE
M1 Support

### ISSUE THREAD

**Issue by vitalyster** [tigase/beagle-im#89]
Appstore version does not work on Apple Silicon. With Rosetta it crashed on start.

**Comment by hantu85** [comment]
BeagleIM worked just fine on M1 with Rosetta when it was released. The new version, which is now in beta as it is still not stable, is working on M1 and contains a build for M1 CPU architecture.

Issue (if you are experiencing it) will be fixed in the new version when it is released.

**Comment by vitalyster** [comment]
Crash with Rosetta:
```
% arch -x86_64 /Applications/BeagleIM.app/Contents/MacOS/BeagleIM
could not get authorization for notifications true nil
found account = xxx@xxx , jid = yyy@yyy , count = 1
[...]
zsh: illegal hardware instruction
```

**Comment by hantu85** [comment]
As I've already stated:
> The new version, which is now in beta as it is still not stable, is working on M1 and contains a build for M1 CPU architecture.
>
> Issue (if you are experiencing it) will be fixed in the new version when it is released.

You need to wait for a new version to be released.

**Comment by michaelblyons** [comment]
5.0 is out now. Try again?

**Comment by vitalyster** [comment]
Works now
