### ISSUE TITLE
Autocorrect returning on MacOS

### ISSUE THREAD

**Issue by Sultanned** [tigase/beagle-im#91]
**Describe the bug**
I turned off the "Correct spelling automatically" checkmark, but after some time it reverts back. What shall I do? What's the problem here?

**Expected behavior**
I expect it not to revert back without my knowledge.

**Desktop**
 - OS: MacOS
 - App: BeagleIM
 - Version: 4.1
![Screenshot 2021-09-01 at 16 15 29](https://user-images.githubusercontent.com/89920160/131678739-863f88f8-32ef-42d4-9804-eeffdd9863f1.png)

**Comment by hantu85** [comment]
You are using an option to temporarily disable spellchecking in the current view. If you want to disable it always go to `Preferences` and uncheck `Spellchecking`.
